# Check how many AXIEs the player has as for now.

# REPLACE THE txFrom field with player address.

query MyQuery {
  ethereum(network: ethereum) {
    address(address: {is: "0x445ba6F9f553872Fa9cDC14F5c0639365b39C140"}) {
      balances(currency: {is: "REPLACE THIS WITH THE PLAYER ADDRESS"
      # e.g. "0xf5b0a3efb8e8e4c201e2a935f110eaaf3ffecb8d"
      }) {
        value
      }
    }
  }
}
